### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by shreyakoley020102**
Omnifood: A simple website for food lovers using HTML and CSS

### CODE REVIEW

**Comment by manjunani** [comment]
Hi @shreyakoley020102 , Could you move your files into one folder and commit Because your files are getting added to Base Directory "Web Dev Projects"
It will be nice if you add all your files to one Folder

**Review by manjunani — CHANGES_REQUESTED** [review]
Hi @shreyakoley020102 , Could you move your files into one folder and commit Because your files are getting added to Base Directory "Web Dev Projects"
It will be nice if you add all your files to one Folder

Thanks for Understanding

**Comment by shreyakoley020102** [comment]
Now I've made the changes, btw I'm very sorry

**Review by manjunani — APPROVED** [review]
Thanks for the Update

**Pull request merged**
