### PR TITLE
added a Dice program which I made using Python and Turtle

### PR DESCRIPTION
**Pull request by Rudra50000**
Hi! I am Rudraneel Mandal and I created a Dice program using Python and Turtle.

### CODE REVIEW

**Comment by manjunani** [comment]
Kindly Update the readme file in the Python folder too..

**Comment by Rudra50000** [comment]
Yes sure.

**Comment by Rudra50000** [comment]
I have updated the readme.md file in the python folder

**Comment by Rudra50000** [comment]
Thanks!

**Pull request merged**
